### ISSUE TITLE
Rom Please

### ISSUE THREAD

**Issue by brkkr** [nukep/undertale-nes#3]
Can You Give the nes rom or ı will die

**Comment by brkkr** [comment]
Pleaseeeeeeeeeee

**Comment by brkkr** [comment]
fö,dö
 
w
ef
ef
cçşösöcşc

dc
dv
d
f


fö

**Comment by nukep** [comment]
Hi, sorry for the delay. You can find a build here:

https://github.com/nukep/undertale-nes/releases/tag/0.1.0
