### ISSUE TITLE
error building the rom

### ISSUE THREAD

**Issue by ghost** [nukep/undertale-nes#4]
nothing to do!make *** {Makefile:5 bin/main.nes} Error 1
Any idea?

**Comment by NEWLuigi64** [comment]
I don't have an idea but I do have something to say...

Can you revive this project? I would really love to see new updates of this!

**Comment by ghost** [comment]
> I don't have an idea but I do have something to say...
> 
> Can you revive this project? I would really love to see new updates of this!

It is difficult, the nes has many limitations, I do not think the author will continue the project

**Comment by ghost** [comment]
Fixed, was a dependency error
